services:
  mcpo:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: mcpo
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - MCPO_CONFIG_PATH=/app/config.json
      - MCPO_DATA_DIR=/app/data
      - MCPO_HOST=0.0.0.0
      - MCPO_PORT=8000
      - MCPO_API_KEY=${MCPO_API_KEY}
      - MCPO_HOT_RELOAD=${MCPO_HOT_RELOAD:-true}
      - EXA_API_KEY=${EXA_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    command: ["--config", "/app/config.json", "--host", "0.0.0.0", "--port", "8000", "--api-key", "${MCPO_API_KEY}", "--hot-reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes: {}